### ISSUE TITLE
🐛 나브바 컴포넌트 데이터 조회에 대한 오류

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#16]
## 🔎 어떤 버그인가요?
<img width="1061" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/ebccb90f-f002-4f3b-91f1-4296ed2e499c">

나브바 컴포넌트에서 데이터 조회를 한 경우, 해당 부분 로드에 오류가 발생합니다.
- 데이터는 잘 표시됨
- **connectedCallback() 부분이 전부 동작하지 않음.**
    - `nav_bar.js`의 이벤트가 모두 동작하지 않음

## 📝 어떤 상황에서 발생한 버그인가요?
- 이 부분에서 user를 데이터에서 불러올 때 오류가 발생해요..

```html
    <div class="d-flex justify-content-center align-self-center">
      <p class="mb-0 mx-2 align-self-center" style="color: white;">lv.{{user.profile.level}} {{user.profile.id}}</p>
      <img src="{{user.profile.avatar.url}}" style="width:3em; height:3em; border-radius: 50%;" id="profileCardModalBtn" class="img-button mx-3">
    </div>
```

뷰에서 데이터를 가져오는 부분에서 오류가 발생한 것 같아요..

## 🧪 예상 결과
> 데이터를 잘 불러온다.
> 이벤트 리스너의 정상 작동.

## ✅ To-do
- [ ] 문제 원인 분석
- [ ] 문제 해결

## 🔈ps
서버에서 fetch 해올 정보이기 때문에 해당 부분을 적용하는 것이 의미 없다면 이슈 그냥 닫아주셔도 됩니다!

**Comment by bartshin** [comment]
브랜치 이름, 파일, 코드 위치 알려주세요
feat/nav-bar에서 nav_bar.js connected_callback 는 실행되네요
마지막 오류의 data는 FriendView 에 있나요?
말씀드린것처럼 Component에서 데이터를 가져오려면 상위 뷰가 그 데이터를 가지고 있어야 해요
