### ISSUE TITLE
🐛 음악이 중첩되는 오류

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#38]
## 🔎 어떤 버그인가요?
게임페이지를 벗어나도 음악이 꺼지지 않아요.
게임페이지를 다시 접속하면 음악이 중첩됩니다.

## 📝 어떤 상황에서 발생한 버그인가요?
홈페이지 - 모드 페이지 - 매칭 페이지 - 게임 페이지**(음악 시작)** - 뒤로가기(매칭 페이지:  **음악 꺼지지 않음**) - 게임 페이지 진입(**음악 중첩**)

## 🧪 예상 결과
- 페이지 벗어날 시 음악 종료

## ✅ To-do
- [ ] 페이지를 벗어날 시 음악 종료

**Comment by bartshin** [comment]
코드 보시면 음악 종료 함수가 있는데 아직 화면에 연결을 제대로 안했습니다
