### ISSUE TITLE
🐛 게임 엔진 오류

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#47]
## 🔎 어떤 버그인가요?
> 공이 장에물의 엣지에 맞을 때 탈출 하지 못하는 오류가 발생합니다.

## 📝 어떤 상황에서 발생한 버그인가요?
- 장애물의 엣지에 맞는 경우
    - 시작하자마자 걸리는 경우도 있음

## 🧪 예상 결과
> 엣지에서의 부드러운 전환

## ✅ To-do
- [ ] 게임 엔진 수정

## 스크린샷

https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/3bc6773b-eb7b-4c94-bd8d-cb4631bc04bb

**Comment by bartshin** [comment]
최근 커밋에 공 리셋버튼 구현되어있습니다
