### ISSUE TITLE
✨ jwt를 이용한 인증, 인가 처리 요청

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#52]
## 📝 어떤 기능인가요?
>  jwt를 이용한 인증, 인가 처리 요청

## ✅ 작업 상세 내용
- [x] 로그인 버튼과 42 OAuth url 연결
- [x] 발급 받은 토큰 저장
- [x] 모든 fetch API에 토큰 정보 헤더로 전달
- [x] access 토큰이 만료된 경우 refresh 토큰 이용하여 재 발급 로직 추가

## 📚 참고할만한 자료
> 선택사항입니다

**Comment by ohhamma** [comment]
백엔드 코드를 프론트 코드와 연결하는 과정에서 수정이 필요함을 느껴 앞으로 변경될 로직에 대해서 설명드립니다.

우선 `redirect_uri`를 프론트 주소(http://127.0.0.1:8080/login) 로 변경해두었습니다.
프론트에서는 [42API 문서](https://api.intra.42.fr/apidoc/guides/web_application_flow)에 명시되어 있는 주소로 `code` 값을 받아오면 됩니다.
이후 백의 callback 엔드포인트인 http://127.0.0.1:8000/users/42/callback/ 로 해당 값을 전달해주세요.

정리하자면, 아래와 같은 플로우로 로그인 과정이 이루어집니다.
> 1. 프론트에서 구글 로그인 창으로 연결
> 2. 로그인이 끝나면 인가코드와 함께 redirect_uri로 설정된 프론트의 주소로 이동
> 3. 해당 주소에서 axios 등으로 백의 callback 엔드포인트 호출로 회원가입/로그인

더 자세한 내용은 [참고자료](https://velog.io/@hnnynh/OAuth-2.0%EA%B3%BC-Django%EC%9D%98-%EA%B5%AC%EA%B8%80-%EC%86%8C%EC%85%9C%EB%A1%9C%EA%B7%B8%EC%9D%B8)를 읽어보시기 바랍니다.
