### ISSUE TITLE
✨ 인증되지 않은 유저에게만 login page를 보여주도록 하기

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#53]
## 📝 어떤 기능인가요?
> 인증되지 않은 유저에게만 login page를 보여줄 수 있도록 하기.
로그인 한 유저의 토큰이 유효할 때는 home page를 볼 수 있도록 해야할 것 같아요.

## ✅ 작업 상세 내용
- [ ] TODO1
- [ ] TODO2
- [ ] TODO3

**Comment by bartshin** [comment]
`
if (!isLogged) {
  window.location.assign("/login") 
}
`
로그인 확인 가능해지면 
바로 실행하면 될 거 같습니다
