### ISSUE TITLE
🐛 {{data}}에 대해 서버로 요청이 들어가는 오류가 있어요.

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#7]
## 🔎 어떤 버그인가요?
> `{{data}}`에 대해 서버로 요청이 들어가는 오류가 있어요.

## 📝 어떤 상황에서 발생한 버그인가요?
home view에서 사용하는 data를 호출하도록 하는 부분이 실제 url src인 것처럼 서버로 요청을 보내는 상황을 포착했습니다.
data를 호출하여 받아온 url은 잘 받아와서 요청을 띄워주고 있어요.
<img width="795" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/2136e49c-ce86-47b1-954a-91f3adc9682e">

## 🧪 예상 결과
> 오류가 나면 안됩니다.
<img width="727" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/a51d988e-5f7b-4fba-ad26-585ed6529a80">

## ✅ To-do
- [x] 쿠키 문제일 수 있어서 다른 환경에서 한 번 더 해보겠습니다.
    - 로직 안에 문제가 있을 것 같습니다. 
- [ ] 원인 분석
- [ ] 문제 해결

**Comment by bartshin** [comment]
img src에 url을 넣으면 요청을 보내는 것으로 되어있습니다
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by Seotephen** [comment]
<img width="2560" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/b701e0db-ed78-48eb-98a7-4808ec3adf0b">

innerHTML을 살펴보아도 이미지 src에 {{friend.avatar.url}}이 없는데도 요청을 보냅니다..
어떻게 된 영문인지 모르겠어요.

<img width="2560" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/1710aee4-f7bc-4692-bca1-7c43ae501873">

**Comment by bartshin** [comment]
https://github.com/bitbit-Merry-go-round/Transcendence-FE/blob/develop/front/srcs/views/friend/friend_view.html
```html
<img src="{{friend.avatar.url}}" style="width:3em; height:3em; border-radius: 50%;" id="profileCardModalBtn" class="img-button mx-3">
``` 
이 부분 아닌가요?
맨 위에는 home_view로 되어있는데 댓글은 friend_view 네요
어느 브랜치 어느 파일에서 생긴 문제인가요?
