### ISSUE TITLE
🐛 게임 바가 화면을 나갔어요.

### ISSUE THREAD

**Issue by Seotephen** [bitbit-Merry-go-round/Transcendence-FE#78]
## 🔎 어떤 버그인가요?
- 게임 바가 화면을 나갔어요.

## 📝 어떤 상황에서 발생한 버그인가요?
- 바가 작아지는 아이템을 사용한 뒤 공을 받으러 움직였는데 바가 게임 화면을 탈출했어요.
- 한 번 나간 뒤에는 돌아올 수 없습니다.

## 🧪 예상 결과
- 바가 나가지지 않음.

## ✅ To-do
- [ ] 오류 해결

## 📚 참고할만한 자료
<img width="1513" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-FE/assets/99523863/b0f0ed4f-1235-4088-9915-2d606aa7a493">

**Comment by bartshin** [comment]
버그를 일부러 만들어서 확인은 못했지만 수정했습니다 !
확인은 여기서 할 수 있습니다 http://simpsons.iptime.org:8080/game#debug
